spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/rocket
        username: root
        password: 123456
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
host:
    ip: 127.0.0.1
    port: 9876