server:
    port: 8080
    context-path: /
spring:
    profiles:
        active: dev
    freemarker:
        template-loader-path: classpath:/templates
    mvc:
        static-path-pattern: /static/**